<script setup lang="ts">
import { onMounted, ref } from 'vue'
import { useRoute } from 'vue-router'
import { message } from 'ant-design-vue'
import { exportProvenanceReport, getLifecycleTimeline, listAssetVersions } from '@/services/authorizationProvenanceApi'
import ThreeDViewer from '@/components/ThreeDViewer.vue'
const route = useRoute(); const assetCode = String(route.params.assetCode || ''); const loading = ref(false); const error = ref(''); const versions = ref<any[]>([]); const report = ref<any>(null)
async function load() { loading.value = true; error.value = ''; try { const [versionResponse, timelineResponse] = await Promise.all([listAssetVersions({ assetCode }), getLifecycleTimeline({ assetCode })]); versions.value = versionResponse.data; report.value = timelineResponse.data } catch (e: any) { error.value = e.message || '资产详情加载失败' } finally { loading.value = false } }
async function download() { try { const response = await exportProvenanceReport({ assetCode }); const url = URL.createObjectURL(response.data); const link = document.createElement('a'); link.href = url; link.download = `${assetCode}-provenance-report.json`; link.click(); URL.revokeObjectURL(url) } catch (e: any) { message.error(e.message || '报告导出失败') } }
onMounted(load)
</script>
<template><section class="page"><a-page-header class="header" :title="`资产详情：${assetCode}`" sub-title="版本、授权和链路事实来自后端。"><template #extra><a-button @click="$router.push({ name: 'authorization', query: { assetCode } })">授权管理</a-button><a-button type="primary" @click="download">导出溯源报告</a-button></template></a-page-header><a-alert v-if="error" type="error" show-icon :message="error" class="mb"><template #action><a-button size="small" @click="load">重试</a-button></template></a-alert><a-spin :spinning="loading"><a-row :gutter="16"><a-col :xs="24" :lg="10"><a-card title="版本历史"><a-empty v-if="!versions.length" description="暂无版本数据" /><a-timeline v-else><a-timeline-item v-for="version in versions" :key="version.id" :color="version.status === 'CERTIFIED' ? 'green' : 'blue'"><strong>版本 {{ version.versionNo }}</strong><p><a-typography-text code copyable>{{ version.contentSha256 }}</a-typography-text></p><p>CID：{{ version.cid || '未记录' }}</p></a-timeline-item></a-timeline></a-card><a-card title="3D 藏品展示" class="model-card"><ThreeDViewer /></a-card></a-col><a-col :xs="24" :lg="14"><a-card title="生命周期时间轴"><a-empty v-if="!report?.timeline?.length" description="暂无生命周期事件" /><a-timeline v-else><a-timeline-item v-for="event in report.timeline" :key="`${event.occurredAt}-${event.reference}`" :color="event.status === 'FAILED' ? 'red' : 'green'"><strong>{{ event.type }} · {{ event.status }}</strong><p>{{ event.occurredAt }} · {{ event.reference }}</p><p>{{ event.detail }}</p></a-timeline-item></a-timeline></a-card></a-col></a-row></a-spin></section></template>
<style scoped>.page{padding:16px 20px 24px;background:#f7fbff;min-height:100%}.header,.mb{margin-bottom:16px}.header{border-radius:16px;background:#fff;border:1px solid #e2e8f0}.model-card{margin-top:16px}@media(max-width:767px){.page{padding:12px}}</style>
