<script setup lang="ts">
import { reactive, ref } from 'vue'
import { useRoute } from 'vue-router'
import { message } from 'ant-design-vue'
import { createAuthorization, listAuthorizations, revokeAuthorization } from '@/services/authorizationProvenanceApi'

const route = useRoute(); const assetCode = ref(String(route.query.assetCode || '')); const loading = ref(false); const submitting = ref(false); const error = ref(''); const records = ref<any[]>([])
const form = reactive({ licenseeName: '', licenseeOrganization: '', usageType: 'COMMERCIAL', commercial: true, revenueShareRatio: 0, startsAt: new Date().toISOString(), endsAt: new Date(Date.now() + 30 * 86400000).toISOString() })
async function load() { if (!assetCode.value.trim()) { message.warning('请输入资产编号'); return }; loading.value = true; error.value = ''; try { records.value = (await listAuthorizations({ assetCode: assetCode.value.trim() })).data } catch (e: any) { error.value = e.message || '授权记录加载失败' } finally { loading.value = false } }
async function submit() { if (!assetCode.value.trim() || !form.licenseeName) { message.warning('请填写资产编号和被授权方'); return }; submitting.value = true; try { await createAuthorization({ authorization: { assetCode: assetCode.value.trim(), ...form, revenueShareRatio: Number(form.revenueShareRatio) } }); message.success('授权请求已由后端处理'); await load() } catch (e: any) { message.error(e.message || '授权创建失败') } finally { submitting.value = false } }
async function revoke(id: string) { try { await revokeAuthorization({ authorizationId: id, reason: '前端发起的提前撤销' }); message.success('已撤销并保留历史'); await load() } catch (e: any) { message.error(e.message || '撤销失败') } }
</script>
<template><section class="page"><a-page-header class="header" title="授权管理" sub-title="授权记录、撤销和到期状态均由后端保存；不会在浏览器中伪造合同或链交易。" /><a-card class="mb"><a-space wrap><a-input v-model:value="assetCode" placeholder="资产编号，例如 AST-20260728-ABC123" style="width: min(100%, 330px)" /><a-button type="primary" :loading="loading" @click="load">查询授权</a-button></a-space></a-card><a-row :gutter="16"><a-col :xs="24" :lg="9"><a-card title="发起授权"><a-form layout="vertical"><a-form-item label="被授权机构" required><a-input v-model:value="form.licenseeName" /></a-form-item><a-form-item label="机构备注"><a-input v-model:value="form.licenseeOrganization" /></a-form-item><a-form-item label="授权用途"><a-select v-model:value="form.usageType" @change="form.commercial = form.usageType === 'COMMERCIAL'"><a-select-option value="COMMERCIAL">商用</a-select-option><a-select-option value="NON_COMMERCIAL">非商用</a-select-option></a-select></a-form-item><a-form-item label="分润比例（%）"><a-input-number v-model:value="form.revenueShareRatio" :disabled="!form.commercial" :min="0" :max="100" style="width:100%" /></a-form-item><a-form-item label="开始时间（ISO）"><a-input v-model:value="form.startsAt" /></a-form-item><a-form-item label="结束时间（ISO）"><a-input v-model:value="form.endsAt" /></a-form-item><a-button type="primary" block :loading="submitting" @click="submit">提交授权</a-button></a-form></a-card></a-col><a-col :xs="24" :lg="15"><a-card title="授权历史"><a-alert v-if="error" type="error" show-icon :message="error" class="mb" /><a-spin :spinning="loading"><a-empty v-if="!loading && !records.length" description="输入资产编号后查询授权历史" /><a-list v-else :data-source="records"><template #renderItem="{ item }"><a-list-item><a-list-item-meta :title="item.authorizationNo" :description="`${item.licenseeName} · ${item.usageType} · ${item.startsAt} 至 ${item.endsAt}`" /><a-space><a-tag :color="item.status === 'ACTIVE' ? 'green' : item.status === 'REVOKED' ? 'red' : 'orange'">{{ item.status }}</a-tag><a-button v-if="item.status === 'ACTIVE'" danger size="small" @click="revoke(item.id)">撤销</a-button></a-space></a-list-item></template></a-list></a-spin></a-card></a-col></a-row></section></template>
<style scoped>.page{padding:16px 20px 24px;background:#f7fbff;min-height:100%}.header,.mb{margin-bottom:16px}.header{border-radius:16px;background:#fff;border:1px solid #e2e8f0}@media(max-width:767px){.page{padding:12px}}</style>
