<script setup lang="ts">
import { onMounted, ref } from 'vue'
import { useRoute } from 'vue-router'
import { message } from 'ant-design-vue'
import { traceAsset } from '@/services/authorizationProvenanceApi'
const route = useRoute()
const form = ref({ assetCode: '', hash: '', cid: '', transactionId: '' }); const loading = ref(false); const result = ref<any>(null); const error = ref('')
async function trace() { loading.value = true; error.value = ''; result.value = null; try { const params: any = { ...form.value }; if (!params.transactionId) delete params.transactionId; else params.transactionId = Number(params.transactionId); Object.keys(params).forEach((key) => !params[key] && delete params[key]); result.value = (await traceAsset(params)).data } catch (e: any) { error.value = e.message || '溯源查询失败' } finally { loading.value = false } }
onMounted(() => { const assetCode = route.query.assetCode; if (typeof assetCode === 'string' && assetCode) { form.value.assetCode = assetCode; trace() } })
</script>
<template><section class="page"><a-page-header class="header" title="全链路核验" sub-title="按资产编号、SHA-256、CID 或后端交易记录 ID 查询；多个条件必须属于同一资产。"/><a-card><a-form layout="vertical"><a-row :gutter="12"><a-col :xs="24" :md="12"><a-form-item label="资产编号"><a-input v-model:value="form.assetCode" /></a-form-item></a-col><a-col :xs="24" :md="12"><a-form-item label="SHA-256"><a-input v-model:value="form.hash" /></a-form-item></a-col><a-col :xs="24" :md="12"><a-form-item label="CID"><a-input v-model:value="form.cid" /></a-form-item></a-col><a-col :xs="24" :md="12"><a-form-item label="链交易数据库 ID"><a-input v-model:value="form.transactionId" /></a-form-item></a-col></a-row><a-button type="primary" :loading="loading" @click="trace">核验</a-button></a-form></a-card><a-alert v-if="error" class="mt" type="error" show-icon :message="error"/><a-card v-if="result" class="mt" :title="`核验结果：${result.assetCode}`"><a-alert :type="result.mode === 'DEMO' ? 'warning' : 'info'" show-icon :message="result.disclaimer"/><a-timeline class="mt"><a-timeline-item v-for="event in result.timeline" :key="`${event.occurredAt}-${event.reference}`"><strong>{{ event.type }}</strong><p>{{ event.status }} · {{ event.reference }}</p><p>{{ event.detail }}</p></a-timeline-item></a-timeline></a-card></section></template>
<style scoped>.page{padding:16px 20px 24px;background:#f7fbff;min-height:100%}.header,.mt{margin-bottom:16px}.header{border-radius:16px;background:#fff;border:1px solid #e2e8f0}</style>
